language:
  java

jdk:
  oraclejdk8

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.m2

env:
  global:
    - LIMETRANS_LOGLEVEL=DEBUG
    - LIMETRANS_TRANSFORMATIONQUALITY_APPENDER=Console
