language:
  java

jdk:
  oraclejdk8

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

env:
  global:
    - LIMETRANS_LOGLEVEL=DEBUG
    - LIMETRANS_TRANSFORMATIONQUALITY_APPENDER=Console

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

addons:
  sonarqube:
    token:
      secure: "WkVhNB9CrXqqc+lISupaJ9LeQjbPOJ10sraTdRPnk805KPkNugG2xyk6r95GHochLICogN+kARhzrQ3o6qs4ui9aHXqgXaIlL5Anz7qXk8ifzYvskFyT8eo0ShU3NH/Km5C/uWviIY9TciCCAJxGCA25tBcflTyyGio8HJWRDx5Sr2L4qn8tQJsKTx93y2f8tyGagYYOpbE31eGaM7CJfT5/wI3f3Zv5oVKmlYmVbv3q4FoDK95q2n3Afcjo+ZvJA8zLVOqL8aphwkDvU9bE0eb0fvQnIl2FgaVFzKEQT5MXEm5GVdUrqSvRHRXF7wEa8FpDjVXxeCTOwHU7kZI2p0IqJeVcV/vYERel2cTjCRcIWVp7q0qWdvW1AYayICxzApPUItQKXHJ6LHeCQ9LMvHzXoIRSVzeahZRABAPqbxnT8kTFvy4zDP8Cvclg7UnieLJWb2l6FQQi/ZaUqUN9mBaxyM3rH/bHfXgu6NtIR2BmRC40BQoIpgjQjROFUIo8Chm5NLxbExX9o0Uy9q8lThuIan09minI6dRwBPFiO9WTKz/OzvMDxLu5MEDvPZGECpwX+lhWuzvPgRSv+iJRaLty0RlOiT5bmQd8CwRjdobSR3Th2E1DnvXug5XtNaGJ5BwactfA4cVdbsKzD8TInohppIMxbz7+mfbNK0bOyyM="
    github_token:
      secure: "KUmthfCsGaPC6Pc25s1SofE70eKj5szFHV4/THSKoPaw/vZ9eZSXmMcjjqCHapWVw3DaorEAVEx8uXVkd0K6yb5pKnF8/LpZPncPcrHrftuWZLcYPb0woKD2YsektE0KoFVXhRkCYwct5tG1ieFlxrvNbfwCxSRHlBCJgzTTa68MbFlbVz91jX3a84vh4yB6x3zUnwrGznptYdAV7ilWc7FSXbbXEqb90oNM72RS0xfLoHDp9EZ6VzmUjBr6HSkuXcuu6TWyj6CyNP1MT1UDy+zxO11Pj6UCD9rVMROrOAENqHxxIfK255S+lUDecgvs/n7ONumcoY5YCYutOz9c8YAWobCtAUpn3HgeYZfHcA91zmf+7HA4Yba+Ch7qEK60o9C3gV3HeopVcGVQ7HOhacppFCemv3ZLjaSYqW7ptFgQn2+3okuDaurDJcOBGqlRPB0WcBnEOFHhfoY65KLU6rAkf0Pt27fgxSmrZ/68sv1GYLfW5Qbj03S5/Ikxs3ax7XexoK6MLOHW45PXzxTDR8GB/G/jGiksxVCXTSfcZl4lV2jZ8diT6CzoBX0txl1Tj7e1n/ux8LFHYXlgqnZ/HpFrFrejue7PeI5+7YvGDV/HGNvqbkS7j2jhs4QNUEFMfcxxIqG/APbrp1l+eX8UTGRpgMP2Eg9syNi2Pt7KLmE="
